Support percentiles, verbose, cold-start warming, etc.
AntonBazhal/lambda-shearer pull request #5
Opened 2017-06-03 00:14 UTC by dougmoscrop

2017-06-03 00:15 UTC, dougmoscrop commented on .npmrc
> -//registry.npmjs.org/:_authToken=${NPM_TOKEN}
I hope you don't mind, I just use ~/.npmrc and this makes `npm install` and other things fail if env var is not set.

2017-06-03 00:15 UTC, dougmoscrop commented on README.md
> +        P50: 5565ms
I obviously just typed random things that kind of look like they fit (e.g. between MIN MAX)

2017-06-03 00:15 UTC, dougmoscrop commented on index.js
> -const exit = require('exit');
No need to 'force exit', process will terminate when it has nothing left to do in event loop, and .exitCode can be set.

2017-06-03 00:15 UTC, dougmoscrop commented on lib/Runner.js
> +const PERCENTILES = [50, 66, 75, 80, 90, 95, 98, 99];
I omit 100 because of MAX report

2017-06-03 00:16 UTC, dougmoscrop commented on lib/Runner.js
> +    Object.assign(this, options);
I see no name collisions because of _ used

2017-06-03 00:16 UTC, dougmoscrop commented on lib/Runner.js
> +      .delay(500)
could make it longer, or maybe even wait longer for less MB (since it takes longer to cold start function)

2017-06-03 00:17 UTC, dougmoscrop commented on lib/Runner.js
> +        }, { concurrency: this.concurrency });
behaves like `ab` now?

2017-06-03 00:17 UTC, dougmoscrop commented on lib/Runner.js
> +    return this._getAllocatedMemory()
I did not see reason for self use? everything done via =>

2017-06-04 01:39 UTC, dougmoscrop commented on lib/Runner.js
> +class Runner extends EventEmitter {
Runner class now does nothing to stdout, so can be used as lib (I want to use for serverless plugin!)

2017-06-04 01:39 UTC, dougmoscrop commented on lib/Runner.js
> +            .delay(this.delay)
Is there value in this delay at all? Concurrency w/ Delay, w/o Delay ??

2017-06-04 01:41 UTC, dougmoscrop commented
Ok, I'll stop now. Please review.

2017-06-04 04:20 UTC, AntonBazhal requested changes
Great separation of logic!
1. Removing `.npmrc` would break ci (`circle.yml` needs to be updated)
2. Version bump (to `1.1`, I guess)
3. Some other minor points to discuss

2017-06-04 04:20 UTC, AntonBazhal commented on .npmrc
> -//registry.npmjs.org/:_authToken=${NPM_TOKEN}
This is needed for publishing only. Probably, we should generate this file before publishing from ci.

2017-06-04 04:20 UTC, AntonBazhal commented on README.md
> +        P50: 5565ms
👍

2017-06-04 04:20 UTC, AntonBazhal commented on README.md
> +                     lambda function to be tested with                [required]
`warmup` option is missing

2017-06-04 04:20 UTC, AntonBazhal commented on lib/Runner.js
> +const PERCENTILES = [50, 66, 75, 80, 90, 95, 98, 99];
👍

2017-06-04 04:20 UTC, AntonBazhal commented on lib/Runner.js
> +class Runner extends EventEmitter {
👍

2017-06-04 04:20 UTC, AntonBazhal commented on lib/Runner.js
> +      ? this.payload(i + 1)
I'm OK to move this code here, but it should support payload generation function to be asynchronous.

2017-06-04 04:20 UTC, AntonBazhal commented on lib/Runner.js
> +            .delay(this.delay)
Initially this delay was introduced because I saw TooManyRequests error (or something like that). Not sure about the cause though.

2017-06-04 04:20 UTC, AntonBazhal commented on lib/Runner.js
> +        if (this.warmup) {
Warmup looks useful only with concurrency set to 1, otherwise Lambda would be randomly starting new containers.

2017-06-04 04:20 UTC, AntonBazhal commented on lib/Runner.js
> +      ? this.payload(i + 1)
Why do you increment `i`? I think, having `i == 0` for warmup call is OK.

2017-06-04 04:20 UTC, AntonBazhal commented on bin/lambda-shearer.js
> +runner.run()
The reason to use `exit` was that Node.js has (or had) problems with finalizing cli process in Windows.

2017-06-04 04:20 UTC, AntonBazhal commented on lib/Runner.js
> +          return this._invokeLambda(0);
I used `self` as a sort of future safeguard, but it does not really matter. We can leave `this`.

2017-06-04 13:06 UTC, dougmoscrop commented on bin/lambda-shearer.js
> +runner.run()
Ok, will being it back

2017-06-04 13:06 UTC, dougmoscrop commented on lib/Runner.js
> +      ? this.payload(i + 1)
Yep will fix both

2017-06-04 13:07 UTC, dougmoscrop commented on lib/Runner.js
> +        if (this.warmup) {
Agreed

2017-06-04 14:58 UTC, dougmoscrop commented
Ok, tried to add .npmrc generation in circle deploy step and I believe I addressed all your items.

2017-06-04 14:58 UTC, dougmoscrop commented
Is circle configured to build PRs?

2017-06-05 03:16 UTC, AntonBazhal commented
> Is circle configured to build PRs?

Just turned it on

2017-06-05 12:06 UTC, AntonBazhal approved these changes

2017-06-05 12:11 UTC, AntonBazhal commented
Can you do a dummy push to trigger ci?

2017-06-05 12:46 UTC, dougmoscrop commented
done

2017-06-05 14:31 UTC, merged